name: pixelis
channels:
  - pytorch
  - nvidia # CRITICAL: Add nvidia channel for CUDA-enabled packages
  - conda-forge
  - defaults
dependencies:
  # Conda-managed core dependencies for Linux/NVIDIA
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1 # Or another version compatible with your driver
  - faiss-gpu # CRITICAL: Install the GPU version
  - scipy
  - pip

  # Pip-managed dependencies will be installed in the next step