name: pixelis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipython
  - cudatoolkit=11.8  # For GPU support
  - pip:
    # Core ML/DL Packages
    - torch==2.6.0
    - torchvision==0.20.1
    - torchaudio
    - transformers==4.50.0
    - accelerate==1.6.0
    - datasets==3.5.1
    - safetensors==0.5.3
    - peft==0.15.2
    - huggingface-hub==0.30.2
    - tokenizers==0.21.0
    - sentencepiece==0.2.0
    
    # Training Infrastructure
    - deepspeed==0.16.3
    - ray[default]==2.42.0
    - wandb==0.19.5
    - tensorboard
    - mlflow==3.1.1
    
    # Vision & Multimodal
    - einops==0.8.1
    - qwen-vl-utils==0.0.11
    - opencv-python-headless==4.11.0.86
    - pillow==11.2.1
    - av==14.1.0
    
    # Optimization & Acceleration
    - flash-attn==2.7.4.post1  # May fail on some systems
    - xformers==0.0.28.post3   # May fail on some systems
    - triton==3.1.0
    - liger-kernel==0.5.10
    - vllm==0.7.3              # May fail on CPU-only systems
    
    # Configuration & Utils
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - pyyaml==6.0.2
    - jsonlines
    - filelock==3.18.0
    - tqdm==4.67.1
    - rich==13.9.4
    - packaging==25.0
    - regex==2.24.11.6
    - sympy==1.13.1
    - psutil==6.1.0
    
    # Web & API
    - fastapi==0.115.8
    - uvicorn==0.34.0
    - gradio==5.12.0
    - flask
    - httpx==0.28.1
    - aiohttp==3.11.11
    
    # Development Tools
    - pytest==8.4.1
    - black
    - isort
    - flake8
    - ruff==0.9.3
    - ipykernel
    
    # Special installations (from git)
    - git+https://github.com/huggingface/trl.git@main
    - git+https://github.com/huggingface/transformers.git@main

environment_variables:
  CUDA_HOME: /usr/local/cuda
  MAX_PIXELS: "4014080"
  MIN_PIXELS: "401408"