# Default Pixelis Configuration
# This is the main configuration file that Hydra will load

defaults:
  - model: model_arch
  - training: training_params
  - _self_

# Data configuration
data:
  # Dataset paths
  train_data_path: null
  eval_data_path: null
  test_data_path: null
  
  # Data processing
  max_seq_length: 2048
  preprocessing_num_workers: 4
  overwrite_cache: false
  
  # Data augmentation
  use_augmentation: true
  augmentation_prob: 0.3
  
  # Curriculum learning
  use_curriculum: true
  curriculum_strategy: "difficulty"
  difficulty_bins:
    - "easy"
    - "medium"
    - "hard"
  
  # Sampling
  sampling_strategy: "uniform"
  sample_weights: null
  
  # Data format
  data_format: "json"
  text_column: "text"
  label_column: "label"
  image_column: "image"

# Experiment tracking configuration
experiment:
  # Experiment identification
  experiment_name: "pixelis_experiment"
  run_name: null
  tags: []
  
  # Weights & Biases tracking
  use_wandb: true
  wandb_project: "pixelis"
  wandb_entity: null
  wandb_mode: "online"
  
  # Reproducibility
  track_artifacts: true
  save_code: true
  save_config: true
  save_environment: true
  
  # Multi-seed runs
  num_seeds: 3
  seeds:
    - 42
    - 1337
    - 2024
  
  # Ablation studies
  ablation_mode: false
  ablation_components: []

# System configuration
system:
  # Hardware
  device: "cuda"
  num_gpus: 1
  gpu_ids: null
  
  # Memory management
  max_memory_mb: null
  empty_cache_freq: 100
  
  # Parallelism
  num_workers: 4
  dataloader_num_workers: 4
  
  # Paths
  cache_dir: "./cache"
  temp_dir: "./tmp"
  log_dir: "./logs"
  
  # Logging
  log_level: "INFO"
  log_to_file: true
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Debugging
  debug_mode: false
  profile: false
  detect_anomaly: false

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: |
      Pixelis Training System
      ======================
      A novel vision-language agent with pixel-space reasoning
    footer: |
      Powered by Hydra (https://hydra.cc)
      Use --hydra-help for Hydra specific help
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [console]
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers: [console, file]
    disable_existing_loggers: false
  env: {}
  mode: RUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task: []
  job:
    name: train
    chdir: null
    override_dirname: ""
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: null
    config_sources:
      - path: hydra.conf
        schema: pkg
        provider: hydra
      - path: /configs
        schema: file
        provider: main
      - path: ""
        schema: structured
        provider: schema
    output_dir: ???
    choices:
      model: model_arch
      training: training_params
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false